# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'TradPlusDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'TradPlusAdSDK', '14.3.0'
  pod 'TradPlusAdSDK/FacebookAdapter', '14.3.0'
  pod 'FBAudienceNetwork','6.20.1'
  pod 'TradPlusAdSDK/AdMobAdapter', '14.3.0'
  pod 'Google-Mobile-Ads-SDK','12.9.0'
  pod 'TradPlusAdSDK/UnityAdapter', '14.3.0'
  pod 'UnityAds','4.15.1'
  pod 'TradPlusAdSDK/AppLovinAdapter', '14.3.0'
  pod 'AppLovinSDK','13.3.1'
  pod 'TradPlusAdSDK/TapjoyAdapter', '14.3.0'
  pod 'TapjoySDK','13.4.0'
  pod 'TradPlusAdSDK/VungleAdapter', '14.3.0'
  pod 'VungleAds', '7.5.2'
  pod 'TradPlusAdSDK/IronSourceAdapter', '14.3.0'
  pod 'IronSourceSDK','8.10.0'
  pod 'TradPlusAdSDK/AdColonyAdapter', '14.3.0'
  pod 'AdColony','4.9.0'
  pod 'TradPlusAdSDK/InMobiAdapter', '14.3.0'
  pod 'InMobiSDK' ,'10.8.6'
  pod 'TradPlusAdSDK/MintegralAdapter', '14.3.0'
  pod 'MintegralAdSDK' ,'7.7.9'
  pod 'MintegralAdSDK/All','7.7.9'
  pod 'TradPlusAdSDK/SigmobAdapter', '14.3.0'
  pod 'SigmobAd-iOS', '4.20.1'
  pod 'TradPlusAdSDK/GDTMobAdapter', '14.3.0'
  pod 'GDTMobSDK', '4.15.50'
  pod 'TradPlusAdSDK/PangleAdapter', '14.3.0'
  pod 'Ads-Global', '7.5.0.5'
  pod 'TradPlusAdSDK/StartAppAdapter',  '14.3.0'
  pod 'StartAppSDK','4.11.0'
  pod 'TradPlusAdSDK/TPCrossAdapter', '14.3.0'
  pod 'TradPlusAdSDK/ChartboostAdapter', '14.3.0'
  pod 'ChartboostSDK','9.9.2'
  pod 'TradPlusAdSDK/FyberAdapter', '14.3.0'
  pod 'Fyber_Marketplace_SDK','8.3.8'
  pod 'TradPlusAdSDK/BaiduAdapter', '14.3.0'
  pod 'BaiduMobAdSDK','5.400'
  pod 'TradPlusAdSDK/VerveAdapter', '14.3.0'
  pod 'HyBid','3.6.0'
  pod 'TradPlusAdSDK/YandexAdapter', '14.3.0'
  pod 'YandexMobileAds','7.15.1'
  pod 'TradPlusAdSDK/HeliumAdapter', '14.3.0'
  pod 'ChartboostMediationSDK','5.3.0'
  pod 'ChartboostMediationAdapterChartboost','5.9.9.0.0'
  pod 'TradPlusAdSDK/CSJAdapter', '14.3.0'
  pod 'Ads-CN/BUAdSDK', '7.0.1.1'
  pod 'TradPlusAdSDK/BigoAdapter', '14.3.0'
  pod 'BigoADS','4.9.1'
  pod 'TradPlusAdSDK/TPGoogleIMAAdapter', '14.3.0'
  pod 'GoogleAds-IMA-iOS-SDK','3.26.1'
  pod 'TradPlusAdSDK/BeiziAdapter', '14.3.0'
  pod 'BeiZiSDK-iOS/BeiZiSDK-iOS','4.90.6.1'
  pod 'TradPlusAdSDK/AmazonAdapter', '14.3.0'
  pod 'AmazonPublisherServicesSDK','5.3.0'
  pod 'TradPlusAdSDK/TanxAdapter', '14.3.0'
  pod 'TradPlusTanXSDK','3.5.6'
  pod 'TradPlusAdSDK/KwaiAdsAdapter', '14.3.0'
  pod 'KwaiAdsSDK','1.2.0'
  pod 'TradPlusAdSDK/TaurusXAdapter', '14.3.0'
  pod 'TaurusxAdsSDK','1.8.0'

##测试工具
pod "TPMediationHelper",'1.2.0'
end
