# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'TradPlusDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TradPlusDemo
	
  pod 'TradPlusAdSDK', '7.9.0'
  pod 'TradPlusAdSDK/FacebookAdapter', '7.9.0'
  pod 'FBAudienceNetwork','6.11.2'
  pod 'TradPlusAdSDK/AdMobAdapter', '7.9.0'
  pod 'Google-Mobile-Ads-SDK','9.7.0'
  pod 'TradPlusAdSDK/UnityAdapter', '7.9.0'
  pod 'UnityAds','4.2.1'
  pod 'TradPlusAdSDK/AppLovinAdapter', '7.9.0'
  pod 'AppLovinSDK','11.4.3'
  pod 'TradPlusAdSDK/TapjoyAdapter', '7.9.0'
  pod 'TapjoySDK','12.10.0'
  pod 'TradPlusAdSDK/VungleAdapter', '7.9.0'
  pod 'VungleSDK-iOS', '6.11.0'
  pod 'TradPlusAdSDK/IronSourceAdapter', '7.9.0'
  pod 'IronSourceSDK','7.2.3.1'
  pod 'TradPlusAdSDK/AdColonyAdapter', '7.9.0'
  pod 'AdColony','4.9.0'
  pod 'TradPlusAdSDK/InMobiAdapter', '7.9.0'
  pod 'InMobiSDK/Core' ,'10.0.8'
  pod 'TradPlusAdSDK/MintegralAdapter', '7.9.0'
  pod 'MintegralAdSDK' ,'7.1.8.0'
  pod 'MintegralAdSDK/All','7.1.8.0'
  pod 'TradPlusAdSDK/KuaiShouAdapter', '7.9.0'
  pod 'KSAdSDK', '3.3.27'
  pod 'TradPlusAdSDK/SigmobAdapter', '7.9.0'
  pod 'SigmobAd-iOS', '4.2.1'
  pod 'TradPlusAdSDK/GDTMobAdapter', '7.9.0'
  pod 'GDTMobSDK', '4.13.81'
  pod 'TradPlusAdSDK/PangleAdapter', '7.9.0'
  pod 'Ads-CN', '4.6.0.7', :subspecs => ['BUAdSDK', 'International']
  pod 'TradPlusAdSDK/YouDaoAdapter', '7.9.0'
  pod 'YDADSDK', '2.16.12'
  pod 'TradPlusAdSDK/SmaatoAdapter', '7.9.0'
  pod 'smaato-ios-sdk', '21.7.6'
  pod 'smaato-ios-sdk/Banner', '21.7.6'
  pod 'smaato-ios-sdk/Interstitial', '21.7.6'
  pod 'smaato-ios-sdk/RewardedAds', '21.7.6'
  pod 'TradPlusAdSDK/MaioAdapter', '7.9.0'
  pod 'MaioSDK', '1.6.2'
  pod 'TradPlusAdSDK/MyTargetAdapter', '7.9.0'
  pod 'myTargetSDK', '5.15.2'
#  pod 'TradPlusAdSDK/KidozAdapter', '7.9.0'
  #Kidoz三方不支持pod，请自行下载https://github.com/Kidoz-SDK。
  pod 'TradPlusAdSDK/KlevinAdapter', '7.9.0'
  pod 'KlevinAdSDK','2.9.0.216'
  pod 'TradPlusAdSDK/StartAppAdapter',  '7.9.0'
  pod 'StartAppSDK','4.7.2'
  pod 'TradPlusAdSDK/TPCrossAdapter', '7.9.0'
  pod 'TradPlusAdSDK/ChartboostAdapter', '7.9.0'
  pod 'ChartboostSDK','8.5.0.2'
  pod 'TradPlusAdSDK/FyberAdapter', '7.9.0'
  pod 'Fyber_Marketplace_SDK','8.1.5'
  pod 'TradPlusAdSDK/SuperAwesomeAdapter', '7.9.0'
  pod 'SuperAwesome','8.3.8'
  pod 'TradPlusAdSDK/OguryAdapter', '7.9.0'
  pod 'OgurySdk', '2.1.0'
  pod 'TradPlusAdSDK/BaiduAdapter', '7.9.0'
  pod 'BaiduMobAdSDK','4.881'
  pod 'TradPlusAdSDK/GoogleAdManagerAdapter', '7.9.0'
  pod 'Google-Mobile-Ads-SDK','9.7.0'
  pod 'TradPlusAdSDK/VerveAdapter', '7.9.0'
  pod 'HyBid','2.14.0'
  pod 'TradPlusAdSDK/YandexAdapter', '7.9.0'
  pod 'YandexMobileAds','5.1.0'
  pod 'TradPlusAdSDK/HeliumAdapter', '7.9.0'
  pod 'ChartboostHelium','2.11.0'
  
  # Adapter与TradPlusAdSDK 分离的 pod配置可独立更新
  # Adapter 更新日志可以查看仓库中的CHANGELOG.md
  # 仓库地址：https://github.com/tradplus/pod_tradplus_sdk_adapters

#     pod 'TradPlusAdSDK', '7.9.0'
#     pod 'TradPlusFacebookAdapter', '7.9.0'
#     pod 'TradPlusAdMobAdapter', '7.9.0'
#     pod 'TradPlusUnityAdapter', '7.9.0'
#     pod 'TradPlusAppLovinAdapter', '7.9.0'
#     pod 'TradPlusTapjoyAdapter', '7.9.0'
#     pod 'TradPlusVungleAdapter', '7.9.0'
#     pod 'TradPlusIronSourceAdapter', '7.9.0'
#     pod 'TradPlusAdColonyAdapter', '7.9.0'
#     pod 'TradPlusInMobiAdapter', '7.9.0'
#     pod 'TradPlusMintegralAdapter', '7.9.0'
#     pod 'TradPlusKuaiShouAdapter', '7.9.0'
#     pod 'TradPlusSigmobAdapter', '7.9.0'
#     pod 'TradPlusGDTMobAdapter', '7.9.0'
#     pod 'TradPlusPangleAdapter', '7.9.0'
#     pod 'TradPlusYouDaoAdapter', '7.9.0'
#     pod 'TradPlusSmaatoAdapter', '7.9.0'
#     pod 'TradPlusMaioAdapter', '7.9.0'
#     pod 'TradPlusMyTargetAdapter', '7.9.0'
#     pod 'TradPlusKlevinAdapter', '7.9.0'
#     pod 'TradPlusStartAppAdapter',  '7.9.0'
#     pod 'TradPlusTPCrossAdapter', '7.9.0'
#     pod 'TradPlusChartboostAdapter', '7.9.0'
#     pod 'TradPlusSuperAwesomeAdapter', '7.9.0'
#     pod 'TradPlusFyberAdapter', '7.9.0'
#     pod 'TradPlusOguryAdapter', '7.9.0'
#     pod 'TradPlusBaiduAdapter', '7.9.0'
#     pod 'TradPlusGoogleAdManagerAdapter', '7.9.0'
#     pod 'TradPlusVerveAdapter', '7.9.0'
#     pod 'TradPlusYandexAdapter', '7.9.0'
#     pod 'TradPlusHeliumAdapter', '7.9.0'
#
##     pod 'TradPlusKidozAdapter', '7.9.0'
#   ###    #Kidoz三方不支持pod，请自行下载https://github.com/Kidoz-SDK。
#
#   pod 'FBAudienceNetwork','6.11.2'
#   pod 'Google-Mobile-Ads-SDK','9.7.0'
#   pod 'UnityAds','4.2.1'
#   pod 'AppLovinSDK','11.4.3'
#   pod 'TapjoySDK','12.10.0'
#   pod 'VungleSDK-iOS', '6.11.0'
#   pod 'IronSourceSDK','7.2.3.1'
#   pod 'AdColony','4.9.0'
#   pod 'InMobiSDK/Core' ,'10.0.8'
#   pod 'MintegralAdSDK' ,'7.1.8.0'
#   pod 'MintegralAdSDK/All','7.1.8.0'
#   pod 'KSAdSDK', '3.3.27'
#   pod 'SigmobAd-iOS', '4.2.1'
#   pod 'GDTMobSDK', '4.13.81'
#   pod 'Ads-CN', '4.6.0.7', :subspecs => ['BUAdSDK', 'International']
#   pod 'YDADSDK', '2.16.12'
#   pod 'smaato-ios-sdk', '21.7.6'
#   pod 'smaato-ios-sdk/Banner', '21.7.6'
#   pod 'smaato-ios-sdk/Interstitial', '21.7.6'
#   pod 'smaato-ios-sdk/RewardedAds', '21.7.6'
#   pod 'MaioSDK', '1.6.2'
#   pod 'myTargetSDK', '5.15.2'
#   pod 'KlevinAdSDK','2.9.0.216'
#   pod 'StartAppSDK','4.7.2'
#   pod 'ChartboostSDK','8.5.0.2'
#   pod 'Fyber_Marketplace_SDK','8.1.5'
#   pod 'SuperAwesome','8.3.8'
#   pod 'OgurySdk', '2.1.0'
#   pod 'BaiduMobAdSDK','4.881'
#   pod 'Google-Mobile-Ads-SDK','9.7.0'
#   pod 'HyBid','2.14.0'
#   pod 'YandexMobileAds','5.1.0'
#   pod 'ChartboostHelium','2.11.0'
end
