# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'TradPlusDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TradPlusDemo
	
  pod 'TradPlusAdSDK', '7.1.0'
  pod 'TradPlusAdSDK/FacebookAdapter', '7.1.0'
  pod 'FBAudienceNetwork','6.9.0'
  pod 'TradPlusAdSDK/AdMobAdapter', '7.1.0'
  pod 'Google-Mobile-Ads-SDK','8.13.0'
  pod 'TradPlusAdSDK/UnityAdapter', '7.1.0'
  pod 'UnityAds','4.0.0'
  pod 'TradPlusAdSDK/AppLovinAdapter', '7.1.0'
  pod 'AppLovinSDK','10.3.7'
  pod 'TradPlusAdSDK/TapjoyAdapter', '7.1.0'
  pod 'TapjoySDK','12.8.1'
  pod 'TradPlusAdSDK/VungleAdapter', '7.1.0'
  pod 'VungleSDK-iOS', '6.10.5'
  pod 'TradPlusAdSDK/IronSourceAdapter', '7.1.0'
  pod 'IronSourceSDK','7.1.13.0'
  pod 'TradPlusAdSDK/AdColonyAdapter', '7.1.0'
  pod 'AdColony','4.7.2'
  pod 'TradPlusAdSDK/MoPubAdapter', '7.1.0'
  pod 'mopub-ios-sdk','5.18.2'
  pod 'TradPlusAdSDK/InMobiAdapter', '7.1.0'
  pod 'InMobiSDK/Core' ,'10.0.1'
  pod 'TradPlusAdSDK/MintegralAdapter', '7.1.0'
  pod 'MintegralAdSDK' ,'7.0.5'
  pod 'MintegralAdSDK/RewardVideoAd','7.0.5'
  pod 'MintegralAdSDK/BidRewardVideoAd','7.0.5'
  pod 'MintegralAdSDK/BidInterstitialVideoAd','7.0.5'
  pod 'MintegralAdSDK/InterstitialVideoAd','7.0.5'
  pod 'MintegralAdSDK/InterstitialAd','7.0.5'
  pod 'MintegralAdSDK/BannerAd' ,'7.0.5'
  pod 'MintegralAdSDK/BidBannerAd','7.0.5'
  pod 'MintegralAdSDK/SplashAd','7.0.5'
  pod 'MintegralAdSDK/NativeAdvancedAd','7.0.5'
  pod 'TradPlusAdSDK/KuaiShouAdapter', '7.1.0'
  pod 'KSAdSDK', '3.3.21'
  pod 'TradPlusAdSDK/SigmobAdapter', '7.1.0'
  pod 'SigmobAd-iOS', '3.5.0'
  pod 'TradPlusAdSDK/GDTMobAdapter', '7.1.0'
  pod 'GDTMobSDK', '4.13.50'
  pod 'TradPlusAdSDK/PangleAdapter', '7.1.0'
  pod 'Ads-CN-Beta', '4.3.0.2', :subspecs => ['BUAdSDK', 'International']
  #只使用海外Pangle时 可以将 Ads-CN-Beta 换成 Ads-Global-Beta
  pod 'TradPlusAdSDK/YouDaoAdapter', '7.1.0'
  pod 'YDADSDK', '2.15.3'
  pod 'TradPlusAdSDK/SmaatoAdapter', '7.1.0'
  pod 'smaato-ios-sdk', '21.6.19'
  pod 'smaato-ios-sdk/Banner', '21.6.19'
  pod 'smaato-ios-sdk/Interstitial', '21.6.19'
  pod 'smaato-ios-sdk/RewardedAds', '21.6.19'
  pod 'TradPlusAdSDK/MaioAdapter', '7.1.0'
  pod 'MaioSDK', '1.5.6'
  pod 'TradPlusAdSDK/MyTargetAdapter', '7.1.0'
  pod 'myTargetSDK', '5.14.2'
#  pod 'TradPlusAdSDK/KidozAdapter', '7.1.0'
  #Kidoz三方不支持pod，请自行下载https://github.com/Kidoz-SDK。
#  pod 'TradPlusAdSDK/KlevinAdapter', '7.1.0'
  #Klevin三方不支持线上pod，请自行下载后，使用本地pod接入。https://yky.qq.com/doc/sdk/iOS/
  pod 'TradPlusAdSDK/StartAppAdapter',  '7.1.0'
  pod 'StartAppSDK','4.6.7'
  pod 'TradPlusAdSDK/TPCrossAdapter', '7.1.0'
  pod 'TradPlusAdSDK/ChartboostAdapter', '7.1.0'
  pod 'ChartboostSDK','8.5.0.1'
  pod 'TradPlusAdSDK/FyberAdapter', '7.1.0'
  pod 'Fyber_Marketplace_SDK','8.1.0'
  pod 'TradPlusAdSDK/SuperAwesomeAdapter', '7.1.0'
  pod 'SuperAwesome','8.1.3'
  pod 'TradPlusAdSDK/TPADXAdapter', '7.1.0'
  pod 'TradPlusAdSDK/OguryAdapter', '7.1.0'
  pod 'OguryAds', '2.5.1'
  pod 'OguryChoiceManager', '3.1.8'
  pod 'TradPlusAdSDK/BaiduAdapter', '7.1.0'
  pod 'BaiduMobAdSDK','4.83'
end
